{% set name = "multipledispatch" %}
{% set version = "1.0.0" %}
{% set package = name + "-" + version + ".tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ package }}
    sha256: 5c839915465c68206c3e9c473357908216c28383b425361e5d144594bf85a7e0
  - url: https://raw.githubusercontent.com/mrocklin/multipledispatch/{{ version }}/LICENSE.txt
    fn: LICENSE.txt
    sha256: 8767c8a56a24a69d4bf42561c408bdf3e3ffa40699989aec50b96f4b4351efd9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python >=3.6
    - six

  run:
    - python >=3.6
    - six

test:
  imports:
    - multipledispatch

about:
  home: https://github.com/mrocklin/multipledispatch/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: 'Multiple dispatch'
  doc_url: https://multiple-dispatch.readthedocs.io
  dev_url: https://github.com/mrocklin/multipledispatch/

extra:
  recipe-maintainers:
    - pmlandwehr
    - cpcloud
