schema_version: 1

context:
  version: "0.6.0"

package:
  name: multipledispatch
  version: ${{ version }}

source:
  - url: https://files.pythonhosted.org/packages/source/m/multipledispatch/multipledispatch-${{ version }}.tar.gz
    sha256: a7ab1451fd0bf9b92cab3edbd7b205622fb767aeefb4fb536c2e3de9e0a38bea
  - url: https://raw.githubusercontent.com/mrocklin/multipledispatch/${{ version }}/LICENSE.txt
    sha256: 8767c8a56a24a69d4bf42561c408bdf3e3ffa40699989aec50b96f4b4351efd9
    file_name: LICENSE.txt

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - six
  run:
    - python >=${{ python_min }}
    - six

tests:
  - python:
      imports:
        - multipledispatch
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Multiple dispatch
  homepage: https://github.com/mrocklin/multipledispatch/
  repository: https://github.com/mrocklin/multipledispatch/
  documentation: https://multiple-dispatch.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - cpcloud
    - mgorny
