schema_version: 1

context:
  version: "1.0.0"

package:
  name: multipledispatch
  version: ${{ version }}

source:
  url: https://github.com/mrocklin/multipledispatch/archive/${{ version }}.tar.gz
  sha256: a9eb21390e5051ce28b2ee7acd02bb21885b9e2a4ce6e5fdbb1f338b48b54203

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - six

tests:
  - python:
      imports:
        - multipledispatch
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pytest
        - pytest-benchmark
    files:
      source:
        - multipledispatch/tests/
    script:
      - pytest -vv

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Multiple dispatch
  homepage: https://github.com/mrocklin/multipledispatch/
  repository: https://github.com/mrocklin/multipledispatch/
  documentation: https://multiple-dispatch.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - cpcloud
    - mgorny
