schema_version: 1

context:
  version: "1.0.0"

package:
  name: multipledispatch
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/m/multipledispatch/multipledispatch-${{ version }}.tar.gz
  sha256: 5c839915465c68206c3e9c473357908216c28383b425361e5d144594bf85a7e0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - six

tests:
  - python:
      imports:
        - multipledispatch
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Multiple dispatch
  homepage: https://github.com/mrocklin/multipledispatch/
  repository: https://github.com/mrocklin/multipledispatch/
  documentation: https://multiple-dispatch.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - cpcloud
    - mgorny
